### ISSUE TITLE
Heroku build fails using Bower 1.6.4

### ISSUE THREAD

**Issue by Rdbaker** [qnyp/heroku-buildpack-ruby-bower#26]
Hey guys,

I ran into an issue earlier where I couldn't deploy because of some `MODULE NOT FOUND` error where it couldn't find `node-uuid`. Unfortunately for me, this deploy was one where I was upgrading a lot of versions of things. In looking at the build logs on heroku I found one different was that it was using a newer version of Bower to install dependencies. On a hunch I switched the buildpack to point to the commit `ef7a9876ec12d01ccfa78d1fc7be4bca103231eb` instead of `run-bower/HEAD` and deployed with that and I found that it worked. It *might* not be the version of Bower, but somewhere between those two commits something went wrong. This would be a perfect time to use a [git-bisect](https://git-scm.com/docs/git-bisect) to figure out which commit went wrong.

Let me know if you can/can't repeat this error. We're deploying with ruby-2.0.0 and rails-4.2.4

I'm a big fan of this buildpack so let me know how I can help if you need it!

**Comment by neojin** [comment]
I just noticed the same thing. I am running ruby 2.2.2 and rails 4.2

```
remote: -----> Using Node.js version: 0.10.21
remote: -----> Installing JavaScript dependencies using Bower 1.6.4
remote:        bower                 MODULE_NOT_FOUND Cannot find module 'node-uuid'
remote:  !
remote:  !     Can't install JavaScript dependencies
remote:  !     
remote:  !     Bower 1.0.0 released at 2013-07-23
remote:  !     https://github.com/bower/bower/blob/master/CHANGELOG.md
remote:  !     
remote:  !     Check these points:
remote:  !     * Change from component.json to bower.json
remote:  !     * bower.json requires 'name' option
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
```

**Comment by juno** [comment]
Thank you for reporting and sorry for inconvenience.

Bower 1.6.5 just released at [npm](https://www.npmjs.com/package/bower).
I just updated this buildpack and the build problem seems to be solved.

Could you retry push to Heroku?

**Comment by Rdbaker** [comment]
Okay, I switched it back to `run-bower/HEAD` and deployed a new version and it worked. Thanks for fixing that! :+1:
